db:
  host: subdomain.domain.com
  database: database_name
  user: username
  password: password
  port: 3306
echo_nest_api_key: key
paths:
  - name: home
    path: /path/to/music
  - name: work
    path: C:\alternate\path\to\music
